# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49cd2ad27a20bbe13407ef37e3a47513a9816fadf9ec66cbfa8ceda08201f9017b52561123a05ca5eff9dc732186f88b63f4de86d6fdb23aaccdc8a4a5a9f88f

test:
  secret_key_base: 68ae97ae5778f2cce73dab4bf4ca8504499e300086e557b81d45770b3eb719dc667bad8d50b3cac4cd8fca539169dfd2b35cade2bbf79ea7f542f1ae1135cca8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
